const { Project } = require("../models");

const projectdata = [
  {
    owner: "eclevela-1234",
    repo: "run-buddy",
    link: "https://github.com/eclevela-1234/run-buddy",
    image: "https://opengraph.githubassets.com/1/eclevela-1234/run-buddy",
    language: "HTML",
    languageColor: "#e34c26",
    stars: 0,
    forks: 0,
  },
  {
    owner: "eclevela-1234",
    repo: "git-it-done",
    link: "https://github.com/eclevela-1234/git-it-done",
    description:
      "A showcase for JavaScript based server-side API requests using the public Github API",
    image: "https://opengraph.githubassets.com/1/eclevela-1234/git-it-done",
    language: "CSS",
    languageColor: "#563d7c",
    stars: 0,
    forks: 0,
  },
  {
    owner: "eclevela-1234",
    repo: "taskmaster-pro",
    link: "https://github.com/eclevela-1234/taskmaster-pro",
    description: "A project featuring jQuery and other 3rd party APIs",
    image: "https://opengraph.githubassets.com/1/eclevela-1234/taskmaster-pro",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 0,
    forks: 0,
  },
  {
    owner: "eclevela-1234",
    repo: "Express-Note-Taker",
    link: "https://github.com/eclevela-1234/Express-Note-Taker",
    description: "A note taking app utilizing Express.js",
    image:
      "https://opengraph.githubassets.com/1/eclevela-1234/Express-Note-Taker",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 0,
    forks: 0,
  },
  {
    owner: "eclevela-1234",
    repo: "Final-Project",
    link: "https://github.com/eclevela-1234/Final-Project",
    description:
      "A deeper dive into business analytics at UR Dining via machine learning",
    image: "https://opengraph.githubassets.com/1/eclevela-1234/Final-Project",
    language: "Jupyter Notebook",
    languageColor: "#DA5B0B",
    stars: 0,
    forks: 0,
  },
  {
    owner: "eclevela-1234",
    repo: "Random-Project-Generator",
    link: "https://github.com/eclevela-1234/Random-Project-Generator",
    description:
      "Showcase or skills by developing an app that utilizes at least 2 APIs and one non-Bootstrap CSS library",
    image:
      "https://opengraph.githubassets.com/1/eclevela-1234/Random-Project-Generator",
    language: "HTML",
    languageColor: "#e34c26",
    stars: 0,
    forks: "3",
  },
  {
    owner: "danielcnow",
    repo: "Bootcamp-Challenges",
    link: "https://github.com/danielcnow/Bootcamp-Challenges",
    description: "Challenges for the U of R Web Development Bootcamp",
    image:
      "https://opengraph.githubassets.com/1/danielcnow/Bootcamp-Challenges",
    language: "HTML",
    languageColor: "#e34c26",
    stars: 0,
    forks: 0,
  },
  {
    owner: "danielcnow",
    repo: "password-generator",
    link: "https://github.com/danielcnow/password-generator",
    image: "https://opengraph.githubassets.com/1/danielcnow/password-generator",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 0,
    forks: 0,
  },
  {
    owner: "danielcnow",
    repo: "code-quiz",
    link: "https://github.com/danielcnow/code-quiz",
    image: "https://opengraph.githubassets.com/1/danielcnow/code-quiz",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 0,
    forks: 0,
  },
  {
    owner: "danielcnow",
    repo: "schedule-manager",
    link: "https://github.com/danielcnow/schedule-manager",
    image: "https://opengraph.githubassets.com/1/danielcnow/schedule-manager",
    language: "HTML",
    languageColor: "#e34c26",
    stars: 0,
    forks: 0,
  },
  {
    owner: "danielcnow",
    repo: "weather-app",
    link: "https://github.com/danielcnow/weather-app",
    image: "https://opengraph.githubassets.com/1/danielcnow/weather-app",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 0,
    forks: 0,
  },
  {
    owner: "danielcnow",
    repo: "portfolio-generator",
    link: "https://github.com/danielcnow/portfolio-generator",
    image:
      "https://opengraph.githubassets.com/1/danielcnow/portfolio-generator",
    stars: 0,
    forks: 0,
  },
  {
    owner: "easmsm",
    repo: "employee-tracker",
    link: "https://github.com/easmsm/employee-tracker",
    image: "https://opengraph.githubassets.com/1/easmsm/employee-tracker",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 0,
    forks: 0,
  },
  {
    owner: "whittenburgsa",
    repo: "run-buddy",
    link: "https://github.com/whittenburgsa/run-buddy",
    image: "https://opengraph.githubassets.com/1/whittenburgsa/run-buddy",
    language: "HTML",
    languageColor: "#e34c26",
    stars: 0,
    forks: 0,
  },
  {
    owner: "whittenburgsa",
    repo: "test",
    link: "https://github.com/whittenburgsa/test",
    image: "https://opengraph.githubassets.com/1/whittenburgsa/test",
    stars: 0,
    forks: 0,
  },
  {
    owner: "whittenburgsa",
    repo: "horiseon",
    link: "https://github.com/whittenburgsa/horiseon",
    image: "https://opengraph.githubassets.com/1/whittenburgsa/horiseon",
    language: "HTML",
    languageColor: "#e34c26",
    stars: 0,
    forks: 0,
  },
  {
    owner: "whittenburgsa",
    repo: "savannahportfolio",
    link: "https://github.com/whittenburgsa/savannahportfolio",
    description: "portfolio for skills acquired during bootcamp",
    image:
      "https://opengraph.githubassets.com/1/whittenburgsa/savannahportfolio",
    language: "CSS",
    languageColor: "#563d7c",
    stars: 0,
    forks: 0,
  },
  {
    owner: "whittenburgsa",
    repo: "robot-gladiators",
    link: "https://github.com/whittenburgsa/robot-gladiators",
    image:
      "https://opengraph.githubassets.com/1/whittenburgsa/robot-gladiators",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 0,
    forks: 0,
  },
  {
    owner: "whittenburgsa",
    repo: "taskinator",
    link: "https://github.com/whittenburgsa/taskinator",
    image: "https://opengraph.githubassets.com/1/whittenburgsa/taskinator",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 0,
    forks: 0,
  },
  {
    owner: "tayyjohnson",
    repo: "run-buddy",
    link: "https://github.com/tayyjohnson/run-buddy",
    image: "https://opengraph.githubassets.com/1/tayyjohnson/run-buddy",
    language: "HTML",
    languageColor: "#e34c26",
    stars: 0,
    forks: 0,
  },
  {
    owner: "tayyjohnson",
    repo: "WeekOneChallenge",
    link: "https://github.com/tayyjohnson/WeekOneChallenge",
    description: "Horiseon Accessibility",
    image: "https://opengraph.githubassets.com/1/tayyjohnson/WeekOneChallenge",
    language: "HTML",
    languageColor: "#e34c26",
    stars: 0,
    forks: 0,
  },
  {
    owner: "tayyjohnson",
    repo: "WeekTwoChallenge",
    link: "https://github.com/tayyjohnson/WeekTwoChallenge",
    description: "UofR Coding Bootcamp Week Two Challenge",
    image: "https://opengraph.githubassets.com/1/tayyjohnson/WeekTwoChallenge",
    language: "HTML",
    languageColor: "#e34c26",
    stars: 0,
    forks: 0,
  },
  {
    owner: "tayyjohnson",
    repo: "WeekThreeChallenge",
    link: "https://github.com/tayyjohnson/WeekThreeChallenge",
    image:
      "https://opengraph.githubassets.com/1/tayyjohnson/WeekThreeChallenge",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 0,
    forks: 0,
  },
  {
    owner: "tayyjohnson",
    repo: "codingquiz",
    link: "https://github.com/tayyjohnson/codingquiz",
    description: "This is the week four challenge coding quiz",
    image: "https://opengraph.githubassets.com/1/tayyjohnson/codingquiz",
    language: "JavaScript",
    languageColor: "#f1e05a",
    stars: 0,
    forks: 0,
  },
  {
    owner: "tayyjohnson",
    repo: "workdayscheduler",
    link: "https://github.com/tayyjohnson/workdayscheduler",
    image: "https://opengraph.githubassets.com/1/tayyjohnson/workdayscheduler",
    language: "HTML",
    languageColor: "#e34c26",
    stars: 0,
    forks: 0,
  },
];

const seedProjects = () => Project.bulkCreate(projectdata);

module.exports = seedProjects;
